-- MySQL Script generated by MySQL Workbench
-- 11/18/14 22:54:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Concurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Concurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Concurso` (
  `idC` INT NOT NULL,
  `nombreC` VARCHAR(45) NULL,
  `basesC` VARCHAR(255) NULL,
  `ciudadC` VARCHAR(45) NULL,
  `fechaC` VARCHAR(45) NULL,
  `premioC` INT NULL,
  PRIMARY KEY (`idC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `emailU` VARCHAR(45) NOT NULL,
  `contrasenaU` VARCHAR(45) NOT NULL,
  `tipoU` VARCHAR(1) NOT NULL,
  `estadoU` TINYINT(1) NOT NULL,
  `nombreU` VARCHAR(45) NULL,
  `Concurso_idC1` INT NOT NULL,
  PRIMARY KEY (`emailU`, `Concurso_idC1`),
  CONSTRAINT `fk_Usuario_Concurso1`
    FOREIGN KEY (`Concurso_idC1`)
    REFERENCES `mydb`.`Concurso` (`idC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Concurso1_idx` ON `mydb`.`Usuario` (`Concurso_idC1` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Participante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participante` (
  `direccionP` VARCHAR(45) NOT NULL,
  `telefonoP` INT NULL,
  `nombreLocalP` VARCHAR(45) NULL,
  `horarioP` VARCHAR(45) NULL,
  `paginaWebP` VARCHAR(45) NULL,
  `fotoP` VARCHAR(45) NULL,
  `Usuario_emailU` VARCHAR(45) NOT NULL,
  `Usuario_Concurso_idC1` INT NOT NULL,
  PRIMARY KEY (`Usuario_emailU`, `Usuario_Concurso_idC1`),
  CONSTRAINT `fk_Participante_Usuario1`
    FOREIGN KEY (`Usuario_emailU` , `Usuario_Concurso_idC1`)
    REFERENCES `mydb`.`Usuario` (`emailU` , `Concurso_idC1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pincho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pincho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pincho` (
  `idPi` INT NOT NULL,
  `nombrePi` VARCHAR(45) NULL,
  `precioPi` INT NULL,
  `descripcionPi` VARCHAR(255) NULL,
  `cocineroPi` VARCHAR(45) NULL,
  `numVotosPi` INT NULL,
  `fotoPi` VARCHAR(45) NULL,
  `estadoPi` TINYINT(1) NULL,
  `Participante_Usuario_emailU` VARCHAR(45) NOT NULL,
  `Participante_Usuario_Concurso_idC1` INT NOT NULL,
  PRIMARY KEY (`idPi`, `Participante_Usuario_emailU`, `Participante_Usuario_Concurso_idC1`),
  CONSTRAINT `fk_Pincho_Participante1`
    FOREIGN KEY (`Participante_Usuario_emailU` , `Participante_Usuario_Concurso_idC1`)
    REFERENCES `mydb`.`Participante` (`Usuario_emailU` , `Usuario_Concurso_idC1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pincho_Participante1_idx` ON `mydb`.`Pincho` (`Participante_Usuario_emailU` ASC, `Participante_Usuario_Concurso_idC1` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Pincho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_has_Pincho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Pincho` (
  `Usuario_emailU` VARCHAR(45) NOT NULL,
  `Usuario_Concurso_idC` INT NOT NULL,
  `Pincho_idPi` INT NOT NULL,
  PRIMARY KEY (`Usuario_emailU`, `Usuario_Concurso_idC`, `Pincho_idPi`),
  CONSTRAINT `fk_Usuario_has_Pincho_Usuario1`
    FOREIGN KEY (`Usuario_emailU`)
    REFERENCES `mydb`.`Usuario` (`emailU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pincho_Pincho1`
    FOREIGN KEY (`Pincho_idPi`)
    REFERENCES `mydb`.`Pincho` (`idPi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Pincho_Pincho1_idx` ON `mydb`.`Usuario_has_Pincho` (`Pincho_idPi` ASC);

CREATE INDEX `fk_Usuario_has_Pincho_Usuario1_idx` ON `mydb`.`Usuario_has_Pincho` (`Usuario_emailU` ASC, `Usuario_Concurso_idC` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Pincho1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_has_Pincho1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Pincho1` (
  `Usuario_emailU` VARCHAR(45) NOT NULL,
  `Pincho_idPi` INT NOT NULL,
  PRIMARY KEY (`Usuario_emailU`, `Pincho_idPi`),
  CONSTRAINT `fk_Usuario_has_Pincho1_Usuario1`
    FOREIGN KEY (`Usuario_emailU`)
    REFERENCES `mydb`.`Usuario` (`emailU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pincho1_Pincho1`
    FOREIGN KEY (`Pincho_idPi`)
    REFERENCES `mydb`.`Pincho` (`idPi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Pincho1_Pincho1_idx` ON `mydb`.`Usuario_has_Pincho1` (`Pincho_idPi` ASC);

CREATE INDEX `fk_Usuario_has_Pincho1_Usuario1_idx` ON `mydb`.`Usuario_has_Pincho1` (`Usuario_emailU` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
